//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TST_TicketPriorities
    {
        public TST_TicketPriorities()
        {
            this.TST_SupportTickets = new HashSet<TST_SupportTickets>();
        }
    
        public int PriorityId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TST_SupportTickets> TST_SupportTickets { get; set; }
    }
}
