//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TST_Departments
    {
        public TST_Departments()
        {
            this.TST_Employees = new HashSet<TST_Employees>();
        }
    
        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<TST_Employees> TST_Employees { get; set; }
    }
}
