//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TST_Employees
    {
        public TST_Employees()
        {
            this.TST_SupportTickets = new HashSet<TST_SupportTickets>();
            this.TST_SupportTickets1 = new HashSet<TST_SupportTickets>();
            this.TST_SupportTickets2 = new HashSet<TST_SupportTickets>();
            this.TST_TechNotes = new HashSet<TST_TechNotes>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Email { get; set; }
        public string WorkPhone { get; set; }
        public string CellPhone { get; set; }
        public string UserId { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PhotoUrl { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Notes { get; set; }
        public string SSN { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
    
        public virtual TST_EmployeeStatuses TST_EmployeeStatuses { get; set; }
        public virtual ICollection<TST_SupportTickets> TST_SupportTickets { get; set; }
        public virtual ICollection<TST_SupportTickets> TST_SupportTickets1 { get; set; }
        public virtual ICollection<TST_SupportTickets> TST_SupportTickets2 { get; set; }
        public virtual ICollection<TST_TechNotes> TST_TechNotes { get; set; }
        public virtual TST_Departments TST_Departments { get; set; }
    }
}
