//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TST_TechNotes
    {
        public int TechNoteId { get; set; }
        public int TicketId { get; set; }
        public int TechId { get; set; }
        public string Note { get; set; }
        public System.DateTime NoteSubmittedOn { get; set; }
    
        public virtual TST_Employees TST_Employees { get; set; }
        public virtual TST_SupportTickets TST_SupportTickets { get; set; }
    }
}
