//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TST_SupportTickets
    {
        public TST_SupportTickets()
        {
            this.TST_TechNotes = new HashSet<TST_TechNotes>();
        }
    
        public int TicketId { get; set; }
        public int SubmittedByEmployeeId { get; set; }
        public Nullable<int> TechId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
    
        public virtual TST_Employees TST_Employees { get; set; }
        public virtual TST_Employees TST_Employees1 { get; set; }
        public virtual TST_Employees TST_Employees2 { get; set; }
        public virtual TST_TicketPriorities TST_TicketPriorities { get; set; }
        public virtual TST_TicketStatuses TST_TicketStatuses { get; set; }
        public virtual ICollection<TST_TechNotes> TST_TechNotes { get; set; }
    }
}
